#define UART0_BASE 			0x10100

#define UART_CONTROL			0x0
#define UART_SETTINGS			0x1
#define UART_DATA			0x3
#define UART_TX_FILL			0x4
#define UART_RX_FILL			0x5

#define UART_CONTROL_ENABLE		0x1
#define UART_CONTROL_RESET		0x2
#define UART_SETTINGS_PARITY_TYPE	0x1
#define UART_SETTINGS_PARITY_EN		0x2
#define UART_SETTINGS_STOP_BITS		0x4

#define UART_SETTINGS_DIVISOR_SHIFT	0x3
#define UART_FIFO_SIZE			128

